# -*- coding: utf-8 -*-
"""DSA210 Project Mehmet Eren Tatar

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17QINJcujRL-ltSC7Gq1qAqaVKmUq9jnh
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import f_oneway, ttest_ind

# %matplotlib inline

from google.colab import files


uploaded = files.upload()

traffic = pd.read_csv("traffic.csv")
weather = pd.read_csv("weather.csv")


print("Traffic data:")
display(traffic.head())

print("Weather data:")
display(weather.head())

"""This code loads the traffic and weather datasets into pandas DataFrames using read_csv().Displaying the first few rows helps verify that the data has been imported correctly and that the columns are properly formatted before cleaning and merging.It is the initial data inspection step of the project.

"""

traffic['datetime'] = pd.to_datetime(traffic['datetime'])
weather['time'] = pd.to_datetime(weather['time'])


traffic = traffic[['datetime', 'TI', 'TI_An', 'TI_Av']]

weather = weather[['time', 'tavg', 'tmin', 'tmax', 'prcp', 'wspd', 'pres']]
print("Traffic after column selection:")
display(traffic.head())

print("Weather after column selection:")
display(weather.head())

"""This cell converts the datetime columns into proper timestamp format so they can be resampled, merged, and analyzed chronologically.This step ensures the dataset is clean, consistent, and limited to the features required for the project."""

traffic_daily = (
    traffic
    .set_index('datetime')
    .resample('D')
    .mean()
    .reset_index()
)

print("Daily traffic data:")
display(traffic_daily.head())

traffic_daily['date'] = traffic_daily['datetime'].dt.date
weather['date'] = weather['time'].dt.date

merged = pd.merge(
    traffic_daily,
    weather,
    on='date',
    how='inner'
)

print("Merged data (traffic + weather):")
print(merged.shape)
display(merged.head())

"""The merge() operation aligns both datasets by date, creating a unified table where each row contains both traffic and weather measurements for the same day.

"""

def rain_intensity(x):
    if x == 0:
        return "none"
    elif x < 2:
        return "light"
    elif x < 10:
        return "moderate"
    else:
        return "heavy"

merged['rain_intensity'] = merged['prcp'].apply(rain_intensity)

print("Rain intensity counts:")
print(merged['rain_intensity'].value_counts())

"""This code creates a custom function that converts numerical precipitation values into categorical rain intensity levels such as none, light, moderate, and heavy.
It then applies this function to the weather dataset to generate a new feature (rain_intensity), which will be used in ANOVA and group comparisons.
"""

plt.figure(figsize=(6,4))
plt.hist(merged['TI'].dropna(), bins=30)
plt.title("Daily Traffic Index Distribution (TI)")
plt.xlabel("TI")
plt.ylabel("Frequency")
plt.show()

"""The histogram reveals that most daily traffic index (TI) values fall between 28 and 38, showing a clear concentration around the mid-30s.The graph suggests that Istanbul’s daily traffic intensity is generally stable but occasionally experiences high-congestion outliers."""

plt.figure(figsize=(6,4))
merged.boxplot(column='TI', by='rain_intensity')
plt.title("Traffic Index by Rain Intensity")
plt.suptitle("")
plt.xlabel("Rain Intensity")
plt.ylabel("TI")
plt.show()

"""The boxplot demonstrates that traffic congestion tends to increase as rainfall intensity rises.In contrast, “none” and “light” rain days have lower medians and more compact distributions, suggesting more stable and less extreme congestion levels."""

plt.figure(figsize=(6,4))
merged[['TI_An', 'TI_Av']].plot(kind='box')
plt.title("Asian vs European Side Traffic Indices")
plt.ylabel("Index value")
plt.show()

"""The boxplot highlights that the European side (TI_Av) generally experiences slightly higher traffic congestion compared to the Asian side (TI_An), as indicated by a higher median.The European side also shows a wider spread and more extreme high outliers, suggesting that congestion events are more intense and variable there."""

corr_cols = ['TI', 'TI_An', 'TI_Av', 'prcp', 'tavg', 'wspd', 'pres']
corr_matrix = merged[corr_cols].corr()

plt.figure(figsize=(6,5))
plt.imshow(corr_matrix, cmap='coolwarm', interpolation='nearest')
plt.colorbar()
plt.xticks(range(len(corr_cols)), corr_cols, rotation=45)
plt.yticks(range(len(corr_cols)), corr_cols)
plt.title("Correlation Matrix")
plt.tight_layout()
plt.show()

corr_matrix

"""The correlation heatmap shows a very strong positive correlation between the overall traffic index (TI) and the traffic levels of the Asian and European sides, indicating consistent congestion patterns across the city.Rainfall (prcp) shows a weak positive correlation with TI, suggesting that rainfall alone does not directly drive congestion but may be one contributing factor.
Temperature (tavg), wind speed (wspd), and pressure (pres) exhibit very weak or near-zero correlations with TI, indicating minimal linear relationships between these weather variables and traffic intensity.
"""

merged['rain_intensity'].value_counts()

traffic['datetime'] = pd.to_datetime(traffic['datetime'])
traffic_daily = (
    traffic.set_index('datetime')
           .resample('D')
           .mean()
           .reset_index()
)

traffic_daily['date'] = traffic_daily['datetime'].dt.date
weather['time'] = pd.to_datetime(weather['time'])
weather['date'] = weather['time'].dt.date

merged = pd.merge(
    traffic_daily,
    weather,
    on='date',
    how='inner'
)

merged.head()

def rain_intensity(x):
    if x == 0:
        return "none"
    elif x < 2:
        return "light"
    elif x < 10:
        return "moderate"
    else:
        return "heavy"

merged['rain_intensity'] = merged['prcp'].apply(rain_intensity)
merged['rain_intensity'].value_counts()

groups = merged.groupby('rain_intensity')['TI'].apply(lambda x: x.dropna().values)
for g in groups.index:
    print(g, len(groups[g]))

anova_result = f_oneway(
    groups['none'],
    groups['light'],
    groups['moderate'],
    groups['heavy']
)

print("=== ANOVA RESULTS ===")
print("F-statistic:", anova_result.statistic)


print("p-value    :", "{:.12f}".format(anova_result.pvalue))
alpha = 0.05

if anova_result.pvalue < alpha:
    print("Sonuç: p < 0.05 → H0 is rejected → Rain intensity significantly affects TI.")
else:
    print("Sonuç: p ≥ 0.05 →H0 cannot be rejected → Rain intensity does not significantly affect TI.")

asia = merged['TI_An'].dropna()
europe = merged['TI_Av'].dropna()


t_test_result = ttest_ind(asia, europe, equal_var=False)

print("=== T-TEST RESULTS (Asia vs Europe) ===")
print("t-statistic:", t_test_result.statistic)


print("p-value    :", "{:.12f}".format(t_test_result.pvalue))


alpha = 0.05
if t_test_result.pvalue < alpha:
    print("Sonuç: p < 0.05 → H0 is rejected → Rain intensity significantly affects TI.")
else:
    print("Sonuç: p ≥ 0.05 → H0 cannot be rejected → Rain intensity does not significantly affect TI")